FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias para compilar librerías de hardware
RUN apt-get update && apt-get install -y \
    gcc \
    libc-dev \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements y dependencias específicas de hardware
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir RPi.GPIO

# Copiar scripts
COPY automation.py .
COPY credentials.py .
COPY google-services.json .

CMD ["python", "automation.py"]
